development:
  adapter: postgresql
  encoding: utf8
  database: wtc_dev
  pool: 5
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: wtctest
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: wtc_production
  pool: 5
  username:
  password: